### ISSUE TITLE
Error 1: error in quoting

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm-mu#44] opened 2017-10-26 06:40 UTC
Since my recent contribution #43, something broke, I now regularly get the following error:

	Error 1: error in quoting

I'm still unsure what causes this.  Anyone?

**Comment by tmalsburg** [comment] 2017-10-26 07:34
I didn't have any problems.  Could you please provide instructions for reproducing this problem?  Thank you.

**Comment by Ambrevar** [comment] 2017-10-26 08:40
Sorry, it was so obvious too me that I completely forgot to mention it :p

Recipe:
- `helm-mu`
- Choose a candidate.
- `RET`

It wiill not switch the selected candidate and display the aforementioned error instead.

**Comment by tmalsburg** [comment] 2017-10-26 09:25
I can't reproduce this.  Have you tried with `emacs -Q`?

**Comment by tmalsburg** [comment] 2017-10-26 09:25
I can't reproduce this.  Have you tried it with `emacs -Q`?

**Comment by Ambrevar** [comment] 2017-10-27 15:13
I've taken some time to investigate: this is a very specific issue indeed.
I use Evil mode and I've configured it to be active in the Helm prompt to, so that I can press `dd` to reset the prompt, `cc` to reset+switch to insert mode, etc.

If I press `dd` and then go to insert mode, everything is fine.
If I press `cc` however, Evil resets the line to `\n` with the point right before the newline.
If I move the cursor right I can see that I go one line down.

That spurious new line is the root of the issue.
If I delete it, it does not trigger the issue.
You can also reproduce without Evil by pressing `C-q C-j` in the prompt to manually insert a newline.

The `cc` behaviour does not happen in any other Helm buffer (i.e. it does not insert the extra newline) and I really wonder why.  Is the helm-mu prompt handled in some special way?

**Comment by Ambrevar** [comment] 2017-10-27 15:19
Correction: the `\n` gets inserted in other Helm buffers, but their respective actions can handle trailing newlines gracefully.

mu4e's `mu4e-headers-search` will return `Error 1: error in quoting` if the pattern contains a newline, hence the issue.

We should strip newlines from `helm-pattern` before running the action.  I'll submit a patch.

**Comment by tmalsburg** [comment] 2017-10-27 16:34
Merged.  Thank you for investigating and for the PR.

**Closed** 2017-10-27 16:33 UTC
